In [170]:
N=0
E=0
nodesName = []
nodesEntrance = []
edgesWages = reshape([], 0, 0)
graphMatrix = reshape([], 0, 0)
helpMatrix = reshape([], 0, 0)
toGaussMatrix = reshape([], 0, 0)

function checkNode(myStr)
    for i=1:N
        if nodesName[i]==myStr
            return i
        end
    end
    return -1
end

function openFile(a)
    open("test.txt") do f
        #parsing number of Nodes
        x = readline(f)
        global N=parse(Int64, x)
        
        #parsing Nodes entrance
        for i = 1:N
            x=readline(f)
            tmpA = x[1]
            global nodesName
            push!(nodesName, tmpA)
            tmpB = x[3:end]
            tmpBInt = parse(Int64, tmpB)
            global nodesEntrance
            push!(nodesEntrance, tmpBInt)
        end
        
        #checking Nodes entrance - sum up to 0?
        tmpSum=0
        for i=1:N
            tmpSum+=nodesEntrance[i]
        end
        
        if tmpSum!=0
            throw(DomainError("Sum of node entrance should sum up to 0"))
        end
        
        #N already known
        global edgesWages=zeros(Int64, N, N)
        global graphMatrix=zeros(Int64, N, N)
        
        #Parsing edges with wages
        while !eof(f)
            x=readline(f)
            tmpNodeFrom = x[1]
            tmpNodeTo = x[3]
            index1= checkNode(tmpNodeFrom, N)
            index2= checkNode(tmpNodeTo, N)
            if(index1==-1 || index2 ==-1)
                throw(DomainError("Wrong name of Node"))
            end

            graphMatrix[index1, index2] = 1
        end
    end
end

function buildArray()
    global helpMatrix
    helpMatrix=zeros(Int64, N, N)
    tmp=0
    for i= 1:N
        for j=1:N
            if graphMatrix[i, j]==1
                tmp+=1
                helpMatrix[i, j]=tmp
            end
        end
    end
    global E=tmp
    global toGaussMatrix
    
    toGaussMatrix = zeros(Float64, N,E+1)
    
    for i=1:N
        for j=1:N
            if graphMatrix[i, j]==1
                toGaussMatrix[i, helpMatrix[i,j]]=-1
            elseif graphMatrix[j, i]==1
                toGaussMatrix[i, helpMatrix[j,i]]=1
            end
        end
        toGaussMatrix[i, E+1]=nodesEntrance[i]
    end
end

function main(fileName)
    openFile(fileName)
    graphMatrix
    nodesEntrance
    buildArray()
    helpMatrix
    toGaussMatrix
end

function gauss(A, n)
    for i = 1:n
        for k = i+1:n
            c = -A[k,i]/A[i,i]
            for j = i:n+1
                A[k, j] +=  c * A[i,j]
            end
        end
    end
end

gauss (generic function with 1 method)

In [103]:
n = 4
#A = rand(1.0:100.0, n, n+1)
A=[2.0 2.0 (-1.0) 1.0 7.0; (-1.0) 1.0 2.0 3.0 3.0; 3.0 (-1.0) 4.0 (-1.0) 31.0; 1.0 4.0 (-2.0) 2.0 2.0]
Atemp = copy(A)
Acorrect= A[:, 1:4]
Bcorrect = A[:, 5]
A

4×5 Array{Float64,2}:
  2.0   2.0  -1.0   1.0   7.0
 -1.0   1.0   2.0   3.0   3.0
  3.0  -1.0   4.0  -1.0  31.0
  1.0   4.0  -2.0   2.0   2.0

In [148]:
gauss(Atemp, n)
Atemp

4×5 Array{Float64,2}:
 2.0  2.0  -1.0   1.0       7.0    
 0.0  2.0   1.5   3.5       6.5    
 0.0  0.0   8.5   4.5      33.5    
 0.0  0.0   0.0  -1.76471   3.52941

In [171]:
main("test.txt")

4×5 Array{Float64,2}:
 -1.0   0.0   0.0   1.0   15.0
  1.0  -1.0   0.0   0.0   30.0
  0.0   1.0  -1.0   0.0   40.0
  0.0   0.0   1.0  -1.0  -85.0

In [150]:
matrix=[]
push!(matrix, 'A')
matrix[1]
matrix[1]=="A"

false